In [1]:
import numpy as np
import pandas as pd

In [2]:
items = pd.read_csv('grocery.csv')
ratings = pd.read_csv('ratinggrocery.csv')
users = pd.read_csv('users.csv')

In [10]:
users.sample(10)

      User-ID  Age
1121    22732   65
496     23357   56
470     23383   31
1610    22243   25
718     23135   26
800     23053   15
304     23549   18
1138    22715   29
1546    22307   32
333     23520   19

In [11]:
items.sample(10)

,ISBN,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
0,BB60,national tomato ketchup litre,Rs.90 per pcs,https://pictures.grocerapps.com/original/groce...,http://images.amazon.com/images/P/8445071408.0...,NaN
193,AA612,..face wash,Rs.350 per pcs,https://www.ponds.com/content/dam/unilever/pon...,NaN,NaN
357,AA434,dish washer,###,https://www.ikea.com/in/en/images/products/ski...,http://images.amazon.com/images/P/0312970242.0...,NaN
623,AA143,mitchells jam.,Rs.230 per jar,https://www.mitchells.com.pk/wp-content/upload...,http://images.amazon.com/images/P/8445071408.0...,NaN
474,AA306,maggi noodles,Rs.45 per pcs,https://m.media-amazon.com/images/I/81dpDHc95A...,http://images.amazon.com/images/P/087113375X.0...,NaN
628,AA138,nesvita,Rs.65 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/0804106304.0...,NaN
120,AA692,craving coconut,Rs.120 per box,https://static-01.daraz.pk/p/34f19a8a3414c03ea...,http://images.amazon.com/images/P/087113375X.0...,NaN
1,BB59,kolson macroni packet,Rs.150 per pcs,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/055321215X.0...,NaN
393,AA394,.national soya sauce,Rs.100 per pcs,http://gomart.pk/image/cache/data/incoming/img...,http://images.amazon.com/images/P/1558746218.0...,NaN
412,AA374,macroni,###,https://static-01.daraz.pk/p/ca9b3b13fd592bad2...,http://images.amazon.com/images/P/0060168013.0...,NaN

In [12]:
ratings.sample(10)

      User-ID   ISBN  Item-Rating
934     22917   BB34            2
2323    11175  AA386            5
842     23009   BB37            7
988     22863   BB32            9
2581    11152  AA247            4
1805    11223  AA684            1
2892    11124  AA081            9
1429    22422   BB17            9
1338    22513   BB20            7
2023    11203  AA562            9

In [13]:
print(items.shape)
print(ratings.shape)
print(users.shape)

(754, 6)
(3038, 3)
(1760, 2)

In [14]:
items.isnull().sum()

ISBN               0
Grocery-Title      0
Book-Price         0
Image-URL-M        0
Image-URL-S       28
Image-URL-L      711
dtype: int64

In [15]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Item-Rating    0
dtype: int64

In [16]:
users.isnull().sum()

User-ID    0
Age        0
dtype: int64

In [17]:
items.duplicated().sum()

0

In [18]:
users.duplicated().sum()

0

In [19]:
ratings.duplicated().sum()

0

## Popularity Based Recommender System

In [20]:
ratings_with_name = ratings.merge(items,on='ISBN')
ratings_with_name.sample(10)

,User-ID,ISBN,Item-Rating,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
2865,11125,AA086,4,moong daal,Rs.160 per kg,https://shanfoods.com/wp-content/uploads/2021/...,http://images.amazon.com/images/P/0553582909.0...,NaN
2294,11178,AA400,1,alkarim dates ajwa premium airtight pack,Rs.900 per box,https://esajee.com/media/catalog/product/cache...,http://images.amazon.com/images/P/0842342702.0...,NaN
1414,22617,BB24,4,moong dal,Rs.160 per kg,https://shanfoods.com/wp-content/uploads/2021/...,http://images.amazon.com/images/P/0553582909.0...,NaN
1047,23044,BB38,9,cocomo biscuit,Rs.150 per box,https://www.box.com.pk:8184/assets/product/HyM...,http://images.amazon.com/images/P/1558531025.0...,NaN
2461,11163,AA322,4,kolson macroni fancy large elbow.,Rs.200 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/067176537X.0...,NaN
1676,11234,AA735,6,gillete ultra sensitive shaving gel for men,Rs.600 per pcs,https://cdn11.bigcommerce.com/s-dukhrgn8mp/pro...,http://images.amazon.com/images/P/0375406328.0...,NaN
2235,11183,AA439,1,scotch brite scrub,Rs.65 per pcs,https://cdn.metro-online.pk/dashboard/prod-pic...,http://images.amazon.com/images/P/0441783589.0...,NaN
439,23585,BB56,5,fog body spray….,Rs.755 per pcs,https://cdn2.bigcommerce.com/n-biq04i/ivmp9iza...,http://images.amazon.com/images/P/087113375X.0...,NaN
1026,23065,BB39,8,desi eggs,Rs.400 per dozen,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",http://images.amazon.com/images/P/0966986105.0...,NaN
710,23441,BB51,2,lux soap..,Rs.80 per pcs,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/055321215X.0...,NaN

In [21]:
num_rating_df = ratings_with_name.groupby('Grocery-Title').count()['Item-Rating'].reset_index()
num_rating_df.rename(columns={'Item-Rating':'num_ratings'},inplace=True)
num_rating_df.sample(10)

                    Grocery-Title  num_ratings
12                    ..habib oil            2
579            perfect body spray            2
323        gillete shaving fusion            2
500    national garlic mayonnaise            2
178           chocolate chip nuts            2
322  gillete shaving foam regular            2
646            shan qourma masala            2
31                       .eva oil            2
134             brown shoe shiner            2
332                        grapes            2

In [22]:
avg_rating_df = ratings_with_name.groupby('Grocery-Title').mean()['Item-Rating'].reset_index()
avg_rating_df.rename(columns={'Item-Rating':'avg_rating'},inplace=True)
avg_rating_df.sample(10)

C:\Users\HP\AppData\Local\Temp\ipykernel_14776\3366512465.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  avg_rating_df = ratings_with_name.groupby('Grocery-Title').mean()['Item-Rating'].reset_index()

                         Grocery-Title  avg_rating
272               fair and lovely mens         6.0
547                            novita.         5.0
229           deen's mozzarella cheese         7.0
139                       butter puff.         7.0
528              nescafe cold coffee..         7.0
456                               milk         7.5
543  nivea men sensitive after shaving         8.0
741                      white sugar..         7.0
483                       mouth wash..         8.0
682                            sprite.         4.0

In [23]:
popular_df = num_rating_df.merge(avg_rating_df,on='Grocery-Title')
popular_df.sample(10)

,Grocery-Title,num_ratings,avg_rating
22,.bradys rusk,2,4.5
10,..face wash,2,5.5
692,swiss premium cheese,2,3.5
649,shangrila chilli sauce.,2,8.0
531,nestle everyday.,2,5.5
103,bliss lemon and sage body butter maximum moist...,2,2.0
92,besan flour,2,6.0
628,scotch brite scrub,2,5.0
35,.fresh milk,2,5.5
541,nivea men after shave balm pro,2,6.5

In [24]:
popular_df = popular_df[popular_df['num_ratings']>=30].sort_values('avg_rating',ascending=False).head(50)
popular_df.sample(10)

               Grocery-Title  num_ratings  avg_rating
190           cocomo biscuit           30    4.433333
449       mehran nihari msla           30    4.966667
556          onion vegetable           32    5.000000
213     dalda banaspati ghee           42    5.166667
523  nescafe  coffee special           41    4.560976
100      black pepper spices           30    5.333333
33             .face washer.           30    5.666667
149             capri soap..           32    6.000000
672            slice juice..           30    4.633333
1          mozzarella cheese           30    5.100000

In [25]:
popular_df = popular_df.merge(items,on='Grocery-Title').drop_duplicates('Grocery-Title')[['Grocery-Title','Book-Price','Image-URL-M','num_ratings','avg_rating']]
popular_df.sample(10)

,Grocery-Title,Book-Price,Image-URL-M,num_ratings,avg_rating
0,desi eggs,Rs.400 per dozen,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",30,6.200000
32,mehran nihari msla,Rs.85 per pcs,https://mehrangroup.com/wp-content/uploads/202...,30,4.966667
33,shan karahi msla,Rs.90 per box,https://media.naheed.pk/catalog/product/cache/...,50,4.920000
50,cherry blosom black,Rs.350 per pcs,https://media.naheed.pk/catalog/product/cache/...,30,4.333333
40,fresh honey special,Rs.500 per kg,https://i0.wp.com/post.healthline.com/wp-conte...,30,4.700000
17,salt/namak,Rs.90 per pcs,https://www.foodnavigator.com/var/wrbm_gb_food...,36,5.527778
19,tota rice regular use,Rs.170 per kg,http://cdn.shopify.com/s/files/1/0572/4779/332...,30,5.366667
30,onion vegetable,Rs.100 per kg,https://m.media-amazon.com/images/W/WEBP_40237...,32,5.000000
9,gilete shaving G2,Rs.360 (3 pcs),https://static-01.daraz.pk/p/5b2727d0b4af4c779...,30,5.800000
35,pampers baby drys,Rs.900 (16 pcs),https://www.fatehpharma.com/wp-content/uploads...,30,4.833333

## Collaborative Filtering Based Recommender System

In [26]:
x = ratings_with_name.groupby('User-ID').count()['Item-Rating'] > 2
regular_users = x[x].index
regular_users

Int64Index([11111, 11112, 11113, 11114, 11115, 11116, 11117, 11118, 11119,
            11120,
            ...
            11229, 11230, 11231, 11232, 11233, 11234, 11235, 11236, 11237,
            11238],
           dtype='int64', name='User-ID', length=128)

In [27]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(regular_users)]
filtered_rating.sample(10)

,User-ID,ISBN,Item-Rating,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
2452,11164,AA318,8,national garlic ketchup,Rs.130 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/8445071769.0...,NaN
2432,11166,AA331,6,young's mayonnaise,Rs.240 per pcs,https://cdn.shopify.com/s/files/1/0592/3766/27...,http://images.amazon.com/images/P/0002005018.0...,NaN
2800,11132,AA124,3,beef,Rs.1000 per kg,https://pictures.grocerapps.com/original/groce...,http://images.amazon.com/images/P/0380715899.0...,NaN
1888,11216,AA634,6,sella rice..,Rs.250 per kg,https://cdn.shopify.com/s/files/1/0487/1484/22...,http://images.amazon.com/images/P/3404921038.0...,NaN
1803,11223,AA683,3,saltish,Rs.240 per box,https://gradeonemart.pk/wp-content/uploads/202...,http://images.amazon.com/images/P/0060938412.0...,NaN
2300,11178,AA403,1,.freesh milk,Rs.200 per ltr,https://encrypted-tbn0.gstatic.com/images?q=tb...,http://images.amazon.com/images/P/0679865691.0...,NaN
1972,11208,AA584,3,white polish.,Rs.200 per pcs,https://cdn.metro-online.pk/dashboard/prod-pic...,http://images.amazon.com/images/P/0345260317.0...,NaN
2619,11149,AA240,1,chicken.,Rs.550 per kg,https://www.healthbenefitstimes.com/9/uploads/...,http://images.amazon.com/images/P/0245542957.0...,NaN
1882,11216,AA631,8,mehran nihari masala,Rs.85 per pcs,https://mehrangroup.com/wp-content/uploads/202...,http://images.amazon.com/images/P/080652121X.0...,NaN
1875,11215,AA627,8,mehran qourma masala,Rs.85 per pcs,https://mehrangroup.com/wp-content/uploads/202...,http://images.amazon.com/images/P/0060973129.0...,NaN

In [28]:
y = filtered_rating.groupby('Grocery-Title').count()['Item-Rating']>=1
famous_items = y[y].index
famous_items

Index([' chaat masala', '..adams butter', '..blue band butter',
       '..bradys rusk', '..brilla spaghetti', '..chakki flour', '..chicken',
       '..dettol hand sanitizer', '..eva oil', '..face wash',
       ...
       'white sugar', 'white sugar.', 'white sugar..', 'wipes', 'yogurt',
       'young's mayo garlic mayonnaise', 'young's mayo garlic mayonnaise.',
       'young's mayonnaise', 'youngs honey', 'zeera plus'],
      dtype='object', name='Grocery-Title', length=701)

In [29]:
final_ratings = filtered_rating[filtered_rating['Grocery-Title'].isin(famous_items)]
final_ratings.sample(10)

,User-ID,ISBN,Item-Rating,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
2649,11145,AA209,6,bradys rusk,Rs.80 per pcs,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",http://images.amazon.com/images/P/0671870432.0...,NaN
2370,11172,AA369,5,chicken..,Rs.550 per kg,https://www.healthbenefitstimes.com/9/uploads/...,http://images.amazon.com/images/P/0245542957.0...,NaN
1782,11226,AA696,7,peanut pik.,RS.180 per box,https://i0.wp.com/fairo.pk/wp-content/uploads/...,http://images.amazon.com/images/P/1853262404.0...,NaN
2379,11169,AA350,2,pickles,###,https://encrypted-tbn0.gstatic.com/images?q=tb...,http://images.amazon.com/images/P/0439095026.0...,NaN
2910,11122,AA063,3,sella rice,Rs.250 per kg,https://cdn.shopify.com/s/files/1/0487/1484/22...,http://images.amazon.com/images/P/3404921038.0...,NaN
2094,11196,AA507,5,dettol multipurpose,Rs.300 per pcs,http://cdn.shopify.com/s/files/1/0572/4779/332...,http://images.amazon.com/images/P/074322678X.0...,NaN
2990,11116,AA034,8,sesame,Rs.150 per kg,https://encrypted-tbn0.gstatic.com/images?q=tb...,http://images.amazon.com/images/P/0340767936.0...,http://images.amazon.com/images/P/0340767936.0...
2467,11161,AA302,5,noodles,###,https://upload.wikimedia.org/wikipedia/commons...,NaN,NaN
2039,11201,AA548,6,protex,Rs.70 per pcs,https://cdn.metro-online.pk/dashboard/prod-pic...,http://images.amazon.com/images/P/0425182908.0...,NaN
2307,11177,AA406,9,fresh honey,Rs.500 per kg,https://i0.wp.com/post.healthline.com/wp-conte...,http://images.amazon.com/images/P/0380715899.0...,NaN

In [30]:
pt = final_ratings.pivot_table(index='Grocery-Title',columns='User-ID',values='Item-Rating')
pt.sample(10)

User-ID,11111,11112,11113,11114,11115,11116,11117,11118,11119,11120,...,11229,11230,11231,11232,11233,11234,11235,11236,11237,11238
Grocery-Title,,,,,,,,,,,,,,,,,,,,,
harpic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
.chakki flour,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freesh milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
.kolson macroni fancy large elbow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
young's mayo garlic mayonnaise.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
safeguard hand wash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
omung dobala cream,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
butter biscuit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mango juice.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dettol hand wash.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
pt.fillna(0,inplace=True)

In [32]:
pt.sample(20)

User-ID,11111,11112,11113,11114,11115,11116,11117,11118,11119,11120,...,11229,11230,11231,11232,11233,11234,11235,11236,11237,11238
Grocery-Title,,,,,,,,,,,,,,,,,,,,,
fair and lovely women,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
.white sugar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
toothpaste,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,4.0
novita,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
andalou shaving cream.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
gala biscuit.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cremo reserve womens shaving cream,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,9.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
beef.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
bay leaf,0.0,0.0,0.0,0.0,7.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
lux,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
noodles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
..chicken,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nescafe classic coffee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tota rice.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mehran pulao masala,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mehran tikka masala,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
capri..,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
local sanitizer,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
national tomato ketchup,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dove shampoo,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity_scores = cosine_similarity(pt)
similarity_scores

In [ ]:
similarity_scores.shape

In [ ]:
def recommend(product_name):
    # index fetch
    index = np.where(pt.index==product_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[0:14]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = items[items['Grocery-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Grocery-Title')['Grocery-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Grocery-Title')['Book-Price'].values))
        item.extend(list(temp_df.drop_duplicates('Grocery-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [ ]:
recommend('dew')

In [ ]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [ ]:
items.drop_duplicates('Grocery-Title')

In [ ]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(items,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))